<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" retried="1" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="47110" started-at="2020-06-15T12:26:37 IST" finished-at="2020-06-15T12:27:24 IST">
    <groups>
    </groups>
    <test name="RetryFailedTestCase" duration-ms="47110" started-at="2020-06-15T12:26:37 IST" finished-at="2020-06-15T12:27:24 IST">
      <class name="com.qa.testcases.RetryLogic">
        <test-method status="PASS" signature="launchyahoo()[pri:0, instance:com.qa.testcases.RetryLogic@1786dec2]" name="launchyahoo" is-config="true" duration-ms="18282" started-at="2020-06-15T12:26:37 IST" finished-at="2020-06-15T12:26:56 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchyahoo -->
        <test-method status="SKIP" signature="getYahooTitle()[pri:0, instance:com.qa.testcases.RetryLogic@1786dec2]" name="getYahooTitle" duration-ms="80" retried="true" started-at="2020-06-15T12:26:56 IST" finished-at="2020-06-15T12:26:56 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Yahoo-login] but found [Yahoo - login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Yahoo-login] but found [Yahoo - login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.qa.testcases.RetryLogic.getYahooTitle(RetryLogic.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getYahooTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.RetryLogic@1786dec2]" name="tearDown" is-config="true" duration-ms="1288" started-at="2020-06-15T12:26:56 IST" finished-at="2020-06-15T12:26:57 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="launchyahoo()[pri:0, instance:com.qa.testcases.RetryLogic@1786dec2]" name="launchyahoo" is-config="true" duration-ms="11599" started-at="2020-06-15T12:26:57 IST" finished-at="2020-06-15T12:27:09 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchyahoo -->
        <test-method status="FAIL" signature="getYahooTitle()[pri:0, instance:com.qa.testcases.RetryLogic@1786dec2]" name="getYahooTitle" duration-ms="61" started-at="2020-06-15T12:27:09 IST" finished-at="2020-06-15T12:27:09 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Yahoo-login] but found [Yahoo - login]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Yahoo-login] but found [Yahoo - login]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.qa.testcases.RetryLogic.getYahooTitle(RetryLogic.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getYahooTitle -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.RetryLogic@1786dec2]" name="tearDown" is-config="true" duration-ms="1432" started-at="2020-06-15T12:27:09 IST" finished-at="2020-06-15T12:27:10 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="launchyahoo()[pri:0, instance:com.qa.testcases.RetryLogic@1786dec2]" name="launchyahoo" is-config="true" duration-ms="11301" started-at="2020-06-15T12:27:10 IST" finished-at="2020-06-15T12:27:22 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchyahoo -->
        <test-method status="PASS" signature="loginToYahoo()[pri:0, instance:com.qa.testcases.RetryLogic@1786dec2]" name="loginToYahoo" duration-ms="1081" started-at="2020-06-15T12:27:22 IST" finished-at="2020-06-15T12:27:23 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToYahoo -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.qa.testcases.RetryLogic@1786dec2]" name="tearDown" is-config="true" duration-ms="1713" started-at="2020-06-15T12:27:23 IST" finished-at="2020-06-15T12:27:24 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.testcases.RetryLogic -->
    </test> <!-- RetryFailedTestCase -->
  </suite> <!-- Suite -->
</testng-results>
